name: PDF Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Pull pandoc docker image
      shell: bash
      run: docker pull keyiz/pandoc
    - name: Make PDF via pandoc docker image
      shell: bash
      run: docker run --rm -v `(pwd)`:/systemverilog keyiz/pandoc /systemverilog/scripts/build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: PDF_book
        path: systemverilog.pdf
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: PDF Book Release
        draft: false
        prerelease: true
