name: PDF Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Pull pandoc docker image
      shell: bash
      run: docker pull ghcr.io/kuree/pandoc
    - name: Make PDF via pandoc docker image
      shell: bash
      run: docker run --rm -v `(pwd)`:/systemverilog ghcr.io/kuree/pandoc /systemverilog/scripts/build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: PDF_book
        path: systemverilog.pdf
    - name: Update latest tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: "!contains(github.event.head_commit.message, 'skip pdf')"
    - uses: meeDamian/github-release@2.0
      if: "!contains(github.event.head_commit.message, 'skip pdf')"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        name: PDF book release
        body: Latest PDF release of the book.
        gzip: false
        files: systemverilog.pdf
        allow_override: true
        prerelease: true
